version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install awsebcli
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to Beanstalk
          command: eb deploy PintorticoBackend-env

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master