version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:2.7-jessie

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install awsebcli
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to Beanstalk
          command: eb deploy pintortico-api

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop, master
